
language: swift
xcode_project: Travis101.xcodeproj # path to your xcodeproj folder
xcode_scheme: Travis101Tests
xcode_destination: platform=iOS Simulator,OS=11.4,name=iPhone 8

script:
   - xcodebuild clean build test -project Travis101.xcodeproj -scheme Travis101 -sdk iphonesimulator -destination "platform=iOS Simulator,OS=11.4,name=iPhone 8" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
